# Generated by Django 5.1.6 on 2025-03-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chat_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sent_at']},
        ),
        migrations.AlterModelTable(
            name='user',
            table='chat_user',
        ),
    ]
