# Generated by Django 5.1.6 on 2025-03-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chat',
            table='chat_chat',
        ),
        migrations.AlterModelTable(
            name='message',
            table='chat_message',
        ),
    ]
