# Generated by Django 5.1.6 on 2025-03-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
