# Generated by Django 5.1.6 on 2025-03-26 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_alter_message_attachment_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='archived_by',
            field=models.ManyToManyField(blank=True, related_name='archived_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
