# Generated by Django 5.1.6 on 2025-03-27 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_groupchat_groupmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedGroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archived', to='chat.groupchat')),
                ('users', models.ManyToManyField(related_name='archived_group_chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
